### ISSUE TITLE
failed(error: VidLoader.DownloadError.custom(VidLoader.VidLoaderError(code: -11800, description: "Error Domain=AVFoundationErrorDomain Code=-11800 \"The operation could not be completed\" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12640), NSLocalizedDescription=The operation could not be completed}", localizedDescription: "The operation could not be completed", domain: "AVFoundationErrorDomain")))

### ISSUE THREAD

**Issue by nxnam** [Cyklet/VidLoader#11]
When I downloaded with the

I got an error: 
#### VideoCell: failed(error: VidLoader.DownloadError.custom(VidLoader.VidLoaderError(code: -11800, description: "Error Domain=AVFoundationErrorDomain Code=-11800 \"The operation could not be completed\" UserInfo={NSLocalizedFailureReason=An unknown error occurred (-12640), NSLocalizedDescription=The operation could not be completed}", localizedDescription: "The operation could not be completed", domain: "AVFoundationErrorDomain")))
2020-06-23 11:38:38.366443+0700 VidLoaderExample[1241:277925] Task <4DFDC6EB-196B-4663-8031-8EBDA19587CF>.<1> load failed with error Error Domain=AVFoundationErrorDomain Code=-11800 "The operation could not be completed" UserInfo={NSLocalizedDescription=The operation could not be completed, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundAVAssetDownloadTask <4DFDC6EB-196B-4663-8031-8EBDA19587CF>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundAVAssetDownloadTask <4DFDC6EB-196B-4663-8031-8EBDA19587CF>.<1>"
), NSLocalizedFailureReason=An unknown error occurred (-12640)} [-11800]

**Comment by Cyklet** [comment]
I was trying to access this link through safari and got `HTTP エラー 400.0 - Bad Request` is this a local path URL, how was it generated? I haven't tested URL from local servers.

**Comment by nxnam** [comment]
private func generateDefaultItems() -> [VideoData] {
        let defaultURL = "https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=204639-880806&amp;p=6141&amp;d=629&amp;n=1698&amp;t=d7b7872ee9c19dfd1c4056efc3c228ab&amp;previewflag=0&amp;logging=1"
        
        let defaultURL2 = "https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=204639-880806&p=6141&d=629&n=1698&t=b1b441c918411fd302cda48cf79c8d0a&previewflag=0&logging=1"

        return [VideoData(identifier: "id_1", title: "Item 1", stringURL: defaultURL),
        VideoData(identifier: "id_2", title: "Item 2", stringURL: defaultURL2)]
    }

The same video but link 1 is failing and link 2 is OK. Please see for me. Thanks

**Comment by Cyklet** [comment]
Hi @nxnam the first URL for me is broken, I can't access it in safari or chrome, if an URL can't be open in a browser then it's not downloadable too, can you check first URL and open it in your browser?
