### ISSUE TITLE
I cannot download it on device using iOS 10. Please help me with this problem

### ISSUE THREAD

**Issue by nxnam** [Cyklet/VidLoader#14]

**Comment by Cyklet** [comment]
Hi @nxnam, https://developer.apple.com/support/app-store/ only 2% are using devices with versions smaller then `iOS 12` and soon `iOS 14` will be released and 2% will decrease, I don't know if it's easy to support `iOS 10` OR `iOS 11`. If I have time I will try to add these versions, but I can't promise anything, sorry😟

**Comment by Cyklet** [comment]
iOS 10 is not widely used, we will not add support for this version
