### ISSUE TITLE
Large videos larger than 10 minutes will error and will require a network to play

### ISSUE THREAD

**Issue by nxnam** [Cyklet/VidLoader#17]
I have problems like this. Hope you help

**Comment by Cyklet** [comment]
Hi @nxnam can you provide a link that is failing, so I will be able to check what is happening, it can be other bug, I have already downloaded wwdc videos bigger then 10 min

**Comment by nxnam** [comment]
After downloading -> Turn off the network -> Play video -> The video will be repeated a bit and then continue to play. But it is also not possible to play the entire video

**Comment by nxnam** [comment]
[](https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=207357-891000&amp;p=6141&amp;d=629&amp;n=1698&amp;t=8ae784fb5649e198dd5d5a7a90e248c9&amp;previewflag=0&amp;logging=1)

**Comment by nxnam** [comment]
https://www2.uliza.jp/IF/iphone/iPhonePlaylist.m3u8?v=207357-891000&amp;p=6141&amp;d=629&amp;n=1698&amp;t=8ae784fb5649e198dd5d5a7a90e248c9&amp;previewflag=0&amp;logging=1

**Comment by Cyklet** [comment]
I will take a look, btw I can't open first link, I will use the second one

**Comment by nxnam** [comment]
video I recorded when an error occurred :

https://drive.google.com/file/d/1LshpWLRwJLzpDLryOil99nAvhfFJkLLq/view?usp=sharing

**Comment by Cyklet** [comment]
Hi @nxnam the links expired and I wasn't able to reproduce the bug yet, can you generate them one more time?

**Comment by Cyklet** [comment]
Is video `require a network to play` issue reproducible each time for all videos if you don't have an internet connection?

**Comment by nxnam** [comment]
all videos about 10 minutes long are affected. Short videos are not. When the network is turned on, it plays completely normally.

**Comment by Cyklet** [comment]
Can you paste the code where you prepare `AVPlayer` to play?  (configuration and url/asset setup)
Without internet connection did u try to exit the application and enter again and play short videos? Are these video still playable?

**Comment by nxnam** [comment]
right. Short videos play back normally. A long video only plays 600 seconds and will need network to be able to continue. Otherwise it will stop and cannot be played. I have tried playing with an unencrypted video and played for a long time without having the same problem.

**Comment by Cyklet** [comment]
I have downloaded video from link in `VidLoaderExample` that is in this framework and it is playable entirely without internet connection, are you using `asset(location: URL) -> AVURLAsset?` function to feed `AVPlayer` with asset?

**Comment by nxnam** [comment]
How can I contact separately? Some information I'm not comfortable sharing here.

**Comment by Cyklet** [comment]
messenger -> m.me/petre.plotnic skype -> plotnic_petrea

**Comment by nxnam** [comment]
I use VidLoaderExample and got the same error.
https://drive.google.com/file/d/10FhNwXQZDtDwLv6rH0APjBaBJDlJRVPY/view?usp=sharing

**Comment by Cyklet** [comment]
Strange ( I will try one more time If I will be able to reproduce will be very easy to understand what is going on. Shouldn't be any differences with/without internet connection, if video is downloaded it will play from the same file with the same chunks and with the same key with/without internet connection, this behaviour is really strange.

**Comment by Cyklet** [comment]
I have tried with all bandwidths from your links and all looks good, can you please write here what iOS version you are using and what devices

**Comment by nxnam** [comment]
I tested on iphone 6s and 11 pro max and they all use OS 13.5

**Comment by Cyklet** [comment]
No luck to reproduce it on my side, I even tried biggest bitrate with package lost from settings developer console and same output everything works in offline, I will try more times this evening hope that I will be able to reproduce, btw video that you have sent is not bigger then 10 min maybe that's why I can't reproduce

**Comment by nxnam** [comment]
Last week, you have free time?  I want to talk to you via skype.  So I think it would be better.

**Comment by Cyklet** [comment]
Yes, send a request in the skype and we will discuss when is the best date to have a conversation

**Comment by Cyklet** [comment]
@nxnam I have updated the framework to 1.0.3, I hope bug was fixed

**Comment by Cyklet** [comment]
@nxnam I have released 1.0.4 version where the encryption key is loaded after a delay, thank you again for pointing out how to fix the bug 💪
