### ISSUE TITLE
Error if Master playlist has relative paths

### ISSUE THREAD

**Issue by corifilemanagermobileapp** [Cyklet/VidLoader#2]
if master playlist looks like:
#EXTM3U\n#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=763904,RESOLUTION=854x480,NAME=\"480p\"\nhls-480p-4514b.m3u8?e=1576332017&l=0&h=1f4bd3ed33088853c2431506194e92ad\n#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=423936,RESOLUTION=640x360,NAME=\"360p\"\nhls-360p-2ad79.m3u8?e=1576332017&l=0&h=1f4bd3ed33088853c2431506194e92ad\n#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=155648,RESOLUTION=444x250,NAME=\"250p\"\nhls-250p-3fafa.m3u8?e=1576332017&l=0&h=1f4bd3ed33088853c2431506194e92ad\n

VidLoader throws error .dataConversion.

**Comment by Cyklet** [comment]
Hey, currently the VidLoader works only with absolute paths.
We can make improvements that will handle relative paths, but in this case, the question stands relative to what?

As a solution we can generate a URL from the initial one that was sent to the library, then m3u8 stream URL will become:
`initial_url `+ `stream_url`
For chunk it will be:
`initial_url` + `stream_url` + `chunk_url` 

Will this work for you?

**Comment by corifilemanagermobileapp** [comment]
yes, it will work

**Comment by Cyklet** [comment]
Good evening, I have updated the code to handle relative paths, it would be nice if you could take a look at it. You can switch to `handle-relative-paths` branch and check it, or you can provide me with the URL if it's not a private one and I will check it myself.
After this, I will create a PR and it will be merged in master than a new release will be created.

**Comment by corifilemanagermobileapp** [comment]
no, it doesn't works, i saw you have create an issue to download m3u8 without encryption, i have tried to download m3u8 exactly without encryption. here is a link: https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

**Comment by Cyklet** [comment]
Hey, I have tested the framework with provided URL and it works, if you will have more issues in future please feel free to ask ;)
