### ISSUE TITLE
How to resume AVAssetDownloadTask after restarting app.

### ISSUE THREAD

**Issue by tridorje** [Cyklet/VidLoader#22]
Your code is using AVAssetDownloadTask, But I can't find a way to resume the download if I restart the application in the middle of a download. The download always starts from the beginning on the app restart. I cannot find any mention of resuming downloads in the documentation of the AVAssetDownloadTask. Let me know if anyone has successfully been able to resume download using AVAssetDownloadTask. Thanks

**Comment by Cyklet** [comment]
Hi, sadly as I remember you can't restore the HLS download after application got killed :(  I will try to find more information, maybe something changed this year.

**Comment by tridorje** [comment]
@Cyklet 
I will try on this
https://stackoverflow.com/questions/55748455/ios-resuming-hls-download-and-deleting-partially-downloaded-file

**Comment by Cyklet** [comment]
As I know you are not getting location until download is finished, I am not sure what they described there as I see from comments approach didn't work. I will check it too, client also required this from me and I investigated + contacted apple and as I remember it wasn't not possible, but who knows maybe smth. changed.

**Comment by tridorje** [comment]
Thank you. I will try another way.

**Comment by Cyklet** [comment]
The framework doesn't have this functionality, it is a limitation from AVFoundation
