### ISSUE TITLE
Can you add pause/resume download feature when download process is running?

### ISSUE THREAD

**Issue by tridorje** [Cyklet/VidLoader#23]
When the download process is running, Can you add a pause/resume download feature?
For example:
50% downloading
pause => 50% downloaded
resume => continue to 51%
Thank you so much for your kind.

**Comment by Cyklet** [comment]
Hi @tridorje yes I can add pause and resume functionality, we had pause/resume 2 years ago but ii didn't work very well and we descoped this. I will check what is the behaviour today and I will create 2 public functions `pause` and `resume`.

**Comment by Cyklet** [comment]
Hi, @tridorje I have created a new release 1.0.5 with pause/resume functionality from #25 PR. If you will have any issues with it please feel free to create issues 😉

**Comment by tridorje** [comment]
Thank you, I will check.
