### ISSUE TITLE
After I canceled all the active downloading process, the maximum concurrence downloadable process property is not working correctly.

### ISSUE THREAD

**Issue by tridorje** [Cyklet/VidLoader#26]
For example:
1. From beginning, the maximum concurrence downloadable process property is setted to 2.
2. I start downloading 3 conccurrence video => 2 of them are downloading, another is watting.
3. I call the stopAllAcctiveSeasion function => All of 3 processes are stoped.
4. I re-download all of them again => All the 3 videos are running the download process.

**Comment by Cyklet** [comment]
Hi @tridorje I will take a look
