### ISSUE TITLE
Getting  ResourceLoadingError

### ISSUE THREAD

**Issue by ios-sathish** [Cyklet/VidLoader#6]
Hi Cyklet,

I am facing the issue like : failed(error: VidLoader.DownloadError.custom(VidLoader.VidLoaderError(code: 0, description: "Error Domain=VidLoader.ResourceLoadingError Code=0 \"(null)\"", ", domain: "VidLoader.ResourceLoadingError"))). 

My .m3u8 master file looks like below : 
#EXTM3U
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="150815057359e48d2daa197d47267130b94affe838122b4c0e35891-encryption-00001.key"
#EXTINF:10,
150815057359e48d2daa197d47267130b94affe838122b4c0e35891-00001.ts
#EXTINF:10,
150815057359e48d2daa197d47267130b94affe838122b4c0e35891-00002.ts
#EXTINF:10,
150815057359e48d2daa197d47267130b94affe838122b4c0e35891-00003.ts
#EXTINF:10,
150815057359e48d2daa197d47267130b94affe838122b4c0e35891-00004.ts
#ZEN-TOTAL-DURATION:40.13333
#ZEN-AVERAGE-BANDWIDTH:1329423
#ZEN-MAXIMUM-BANDWIDTH:1400826
#EXT-X-ENDLIST

**Comment by Cyklet** [comment]
Hi @ios-sathish, the .m3u8 file that you have provided is not a master playlist but a variant one, master playlist has next structure:
```
#EXTM3U
#EXT-X-STREAM-INF:BANDWIDTH=150000,RESOLUTION=416x234,CODECS="avc1.42e00a,mp4a.40.2"
http://example.com/low/index.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=240000,RESOLUTION=416x234,CODECS="avc1.42e00a,mp4a.40.2"
http://example.com/lo_mid/index.m3u8
```

you can check description here: https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/creating_a_master_playlist

Do you have the URL of the HLS stream master playlist or only the variant URL?

**Comment by ios-sathish** [comment]
I have only variant URL, it's from the AWS Server please help me to solve this issue.

**Comment by Cyklet** [comment]
Hi, I have bad news, I have tried to download directly the variant file but _AVFoundation_ stops in `.running` state without any error and progress. I assume that _AVAssetDownloadURLSession_ needs the `master` file to identify the codecs and base information to start the download.

I have created a simple test project where I have 2 types of links: one pointing to the master playlist, and the other to the variant file. When I start to download with master playlist everything works as expected, but when I change to the variant link then the download stops and all the tasks remains in the session with `.running` state without any progress or error.
https://bitbucket.org/Cyklet/hlssimpledownload/src/master/

I am stuck at this point, the only thing I believe that we can do is to write an email to **Apple** and ask them if it is possible to use _AVAssetDownloadURLSession_ to download the variant file directly without a master playlist.

**Comment by ios-sathish** [comment]
OK, Thank you for your support.

**Comment by nxnam** [comment]
I have the same error. my m3u8 file: 
#EXTM3U
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://www.honeCryptKey.aspx?v=8871384&s=0"
#EXTINF:4,
112292-487996-00000895_20160609221152/4551-1.crypt.ts

**Comment by Cyklet** [comment]
Ok, I will take a look

**Comment by nxnam** [comment]
https://d2c8xygjp78w85.cloudfront.net/629/112292-487996-00000582_20160609221152.m3u8

You can try with this link. I am getting the same error

**Comment by nxnam** [comment]
#EXTM3U
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2200000
https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001865_20200616185455.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=910800
https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001866_20200616185455.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=422400
https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001867_20200616185455.m3u8
#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000
https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001868_20200616185455.m3u8

i have 4 links like this. How can i choose to download ay the 1st, 2nd or 3rd link?

**Comment by Cyklet** [comment]
> #EXTM3U
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2200000
> https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001865_20200616185455.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=910800
> https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001866_20200616185455.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=422400
> https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001867_20200616185455.m3u8
> #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=64000
> https://d2c8xygjp78w85.cloudfront.net/629/204238-879296-00001868_20200616185455.m3u8
> 
> i have 4 links like this. How can i choose to download at the 1st, 2nd or 3rd link?

@nxnam I have created a new issue https://github.com/Cyklet/VidLoader/issues/7 for this question

**Comment by Cyklet** [comment]
I will renew my investigation towards this issue, appears that on iOS 13.5.1 variant links are working, recently by accident I have tested variant links in the [dummy project](https://bitbucket.org/Cyklet/hlssimpledownload/src/master/) and it succeeded, I am not sure when/where/what changed, I can't find any useful documentation to understand what was different before.

**Comment by Cyklet** [comment]
Variant links with multiple/single encryption key should work now
